### ISSUE TITLE
Request for Code Release Timeline for "From SAM to CAMs"

### ISSUE THREAD

**Issue by HIM** [sangrockEG/S2C#2]
Hi,

Thank you for your amazing work and for sharing your research. I am very interested in your paper titled "From SAM to CAMs: Exploring Segment Anything Model for Weakly Supervised Semantic Segmentation." I have been eagerly waiting for the release of the code as mentioned in the repository.

Could you please provide an update on when the code will be available? It would be incredibly helpful for my research and many others who are following your work.

Thank you very much for your time and effort!

Best regards

**Comment by sangrockEG** [comment]
The code is just released. Thank you for being so interested!
