### ISSUE TITLE
Could you provide the dependency packages and their versions required for the S2C project in a requirements.txt file, please? Thank you!

### ISSUE THREAD

**Issue by lk0429** [sangrockEG/S2C#3]
Could you provide the dependency packages and their versions required for the S2C project in a requirements.txt file, please? Thank you!

**Comment by lk0429** [comment]
Could you provide the dependency packages and their versions required for the S2C project in a requirements.txt file, please? Thank you!

**Comment by sangrockEG** [comment]
Thank you for being so interested.
I just uploaded a yaml file to build the virtual environment.
